# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d1b7eab94b913c916e0ae7d1d25db9fa0250974f5f0e9f09eaf1739e9289cf4d59787b4bca991c61bd90b66578dd7cb2b43965f58cd13ed4405d09d96060206

test:
  secret_key_base: 555624b4b8cee129060684ee4316e2f81d4a543928bbcc0d902345b237192c67e65db01194825631a9dbc5055502f90533b5d335b49962bed33b5f087d11ee41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
